"""null

Revision ID: 19d1a4bc5df3
Revises: 6c5c07793d42
Create Date: 2023-12-10 11:02:58.645336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19d1a4bc5df3'
down_revision: Union[str, None] = '6c5c07793d42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedules', 'room_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedules', 'room_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
