"""owner_id

Revision ID: ced8e8ee9ef1
Revises: 19d1a4bc5df3
Create Date: 2023-12-17 21:06:07.821698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ced8e8ee9ef1'
down_revision: Union[str, None] = '19d1a4bc5df3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('owner_id', sa.Uuid(), nullable=False))
    op.drop_constraint('schedules_course_id_fkey', 'schedules', type_='foreignkey')
    op.create_foreign_key(None, 'schedules', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('users_courses_course_id_fkey', 'users_courses', type_='foreignkey')
    op.drop_constraint('users_courses_user_id_fkey', 'users_courses', type_='foreignkey')
    op.create_foreign_key(None, 'users_courses', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'users_courses', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_courses', type_='foreignkey')
    op.drop_constraint(None, 'users_courses', type_='foreignkey')
    op.create_foreign_key('users_courses_user_id_fkey', 'users_courses', 'users', ['user_id'], ['id'])
    op.create_foreign_key('users_courses_course_id_fkey', 'users_courses', 'courses', ['course_id'], ['id'])
    op.drop_constraint(None, 'schedules', type_='foreignkey')
    op.create_foreign_key('schedules_course_id_fkey', 'schedules', 'courses', ['course_id'], ['id'])
    op.drop_column('courses', 'owner_id')
    # ### end Alembic commands ###
